### ISSUE TITLE
Multiple/simultaneous input nodes bug

### ISSUE THREAD

**Issue by dsepulvedar** [ubidots/ubidots-nodered#12] opened 2019-09-23 20:31 UTC
**Description**
Having multiple input (subscription) nodes in the same flow renders only 1 to connect successfully to Ubidots while the others remains under a "connecting" status, preventing users to subscribe to multiple variables at the same time.

**To Reproduce**
1. Create 2 o more input nodes, each one subscribing to different variable.
2. Deploy the flow
3. Only one of the nodes connect successfully

**Expected behavior**
All the note should connect correctly so one can subscribe to different variable within the same flow

**Screenshots**
Using Ubidots' input node
![image](https://user-images.githubusercontent.com/31961741/65460220-0de16480-de17-11e9-85a2-3fd170e4de02.png)

Using Node-red's raw input MQTT node
![image](https://user-images.githubusercontent.com/31961741/65460298-31a4aa80-de17-11e9-9c43-8283152c458a.png)

**Comment by d4vsanchez** [comment] 2019-10-08 05:28
Duplicate of #11 

Let's follow the discussion there.

Thanks

**Closed by d4vsanchez** 2019-10-08 05:28 UTC
